export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const UPDATE_PIXEL = 'UPDATE_PIXEL';
export const CLEAR_IMAGE = 'CLEAR_IMAGE';
export const MNIST_LOAD_TRAINING_DATA_FINISHED =
    'MNIST_LOAD_TRAINING_DATA_FINISHED';