export const MNIST_UPDATE_IMAGE = 'MNIST_UPDATE_IMAGE';
export const MNIST_UPDATE_PIXEL = 'MNIST_UPDATE_PIXEL';
export const MNIST_CLEAR_IMAGE = 'MNIST_CLEAR_IMAGE';
export const MNIST_LOAD_TRAINING_DATA_FINISHED =
    'MNIST_LOAD_TRAINING_DATA_FINISHED';

export const MNIST_UPDATE_PREDICTION = 'MNIST_UPDATE_PREDICTION';