export const STEP_FORWARD = 'STEP_FORWARD';
export const RESET_GAME = 'RESET_GAME';
export const STEP_BACKWARD = 'STEP_FORWARD';
export const SET_STONE = 'SET_STONE';
export const LOAD_GAME = 'LOAD_GAME';

export const TOGGLE_LIBERTIES_VIEW = 'TOGGLE_LIBERTIES_VIEW';
export const TOGGLE_IS_LIBERTY_VIEW = 'TOGGLE_IS_LIBERTY_VIEW';
export const TOGGLE_FORBIDDEN_VIEW = 'TOGGLE_FORBIDDEN_VIEW';
export const TOGGLE_NEXT_MOVE_VIEW = 'TOGGLE_NEXT_MOVE_VIEW';
