export const TRAIN = 'TRAIN';

export const UPDATE_TRAINING_PROGRESS = 'UPDATE_TRAINING_PROGRESS';

export const UPDATE_WEIGHTS = 'UPDATE_WEIGHTS';
export const GRAPH_SET = 'GRAPH_SET';
export const GRAPH_UPDATE_NODE = 'GRAPH_UPDATE_NODE';