export const STEP_FORWARD = 'STEP_FORWARD';
export const STEP_BACKWARD = 'STEP_FORWARD';
export const SET_STONE = 'SET_STONE';
export const TOGGLE_LIBERTIES_VIEW = 'TOGGLE_LIBERTIES_VIEW';
export const TOGGLE_IS_LIBERTY_VIEW = 'TOGGLE_IS_LIBERTY_VIEW';
export const TOGGLE_FORBIDDEN_VIEW = 'TOGGLE_FORBIDDEN_VIEW';
